trigger:
- main

pool:
  name: MyAgentPool

variables:
  DOTNET_ROOT: 'C:\Program Files\dotnet'
  PATH: 'C:\Program Files\dotnet;$(PATH)'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
